- hosts: all
  vars:
  - distro_name: "{{ ansible_facts['distribution'] }}"

  handlers:
  - name: Restart nfs-utils
    service:
        name: "nfs-utils"
        state: "restarted"
        enabled: yes

  tasks:
  - name: Install package nfs-utils if distro == RedHat (package module)
    package:
       name: "nfs-utils"
       state: present
    when: distro_name == "RedHat" 

  - name: Install package nfs-utils if distro == Debian (package module)
    package:
       name: "nfs-utils"
       state: present
    when: distro_name == "Debian" 
       

  - name: Creating Server backup folder (file module)
    file:
       state: "directory"
       path: "/home/{{ server_user_name }}/Desktop/{{ server_bak_dir }}"


  - name: Starting and enabling Service (service module)     
    service:
       name: "nfs-utils"
       state: "started"
       enabled: yes
   

  - name: creating exports file and sending to server (template module)     
    template:
       dest: "/etc/exports"
       src: "/root/ws2/project2/exports"
    notify:
    - Restart nfs-utils


  - name: Disabling firewall permanantly (firewalld module)  
    firewalld:
       service: "nfs-utils"
       permanent: yes
       immediate: yes
       state: disabled
    
