- name: Let's setup NAS server on remote server
  remote_user: root
  sudo: yes
  
  hosts: all
  #become: yes
  #become_user: root

  vars:
  #- distro_name: "{{ ansible_facts['distribution'] }}"
  - home_dir: "{{ home }}"
  - dir_server: "{{ server_bak_dir }}"

  handlers:
  - name: Restart nfs-utils
    service:
        name: "nfs-utils"
        state: "restarted"
        enabled: yes

  tasks:
  
  #- name: Install package nfs-utils if distro == RedHat (package module)
   # package:
    #   name: "nfs-utils"
     #  state: present
    #become: yes
    #become_user: root
    #when: distro_name == "RedHat"
    #become: true


  #- name: Install package nfs-utils if distro == Debian (package module)
   # package:
    #   name: "nfs-utils"
     #  state: present
    #become: yes
    #become_user: root
    #when: distro_name == "Debian"
    #become: true 

  - name: Creating Server backup folder (file module)
    file:
       state: "directory"
       path: "/{{ home_dir }}/Desktop/{{ dir_server }}"
       #mode: 0755


  - name: Starting and enabling Service (service module)     
    service:
       name: "nfs-utils"
       state: "started"
       enabled: yes
    #become: true
   

  - name: creating exports file and sending to server (template module)     
    template:
       dest: "/etc/exports"
       src: "/tmp/exports"
    notify:
    - Restart nfs-utils


  - name: Disabling firewall permanantly (firewalld module)  
    firewalld:
       service: "nfs-utils"
       permanent: yes
       immediate: yes
       state: disabled
    
